// Generated by Garaga version 1.1.0

//! # Starknet Verification Contract Tests
//!
//! This module contains comprehensive tests for the proof verification contract.
//! The tests use Starknet Foundry's testing features to verify proofs.
//!
//! ## Test Strategy
//! - Use real proof fixtures generated by the garaga CLI
//! - Test both positive (valid proof) and negative (invalid proof) cases

use gigstark_groth16_verifier::groth16_verifier::{
    IGroth16VerifierBN254DispatcherTrait, IGroth16VerifierBN254LibraryDispatcher,
    IGroth16VerifierBN254SafeDispatcherTrait, IGroth16VerifierBN254SafeLibraryDispatcher,
};
use gigstark_escrow::compute_verifier::{
    COMPUTE_OUTCOME_SELLER, GigstarkZkResult, IGigstarkComputeVerifierDispatcher,
    IGigstarkComputeVerifierDispatcherTrait,
};
use snforge_std::fs::{FileTrait, read_txt};
use snforge_std::{
    ContractClassTrait, DeclareResultTrait, declare, start_cheat_block_timestamp,
    start_cheat_caller_address,
};
use starknet::{ClassHash, ContractAddress, SyscallResultTrait};

/// Declare the Groth16VerifierBN254 contract for testing.
///
/// This function declares a new instance of the Groth16VerifierBN254 contract
///
/// # Arguments
/// * `name` - The contract name to declare
///
/// # Returns
/// * `ClassHash` - The class hash of the declared contract
///
/// # Example
/// ```cairo
/// let class_hash = declare_contract("Groth16VerifierBN254");
/// let dispatcher = IGroth16VerifierBN254LibraryDispatcher { class_hash };
/// ```
fn declare_contract(name: ByteArray) -> ClassHash {
    let class_hash = *declare(name).unwrap().contract_class().class_hash;
    class_hash
}

/// Test the verification function verify_groth16_proof_bn254 with a valid proof.
///
/// This test demonstrates the complete verification flow:
/// 1. Declare the verification contract
/// 2. Load a pre-generated proof fixture
/// 3. Verify the proof on-chain
/// 4. Assert that verification succeeds
///
/// ## Test Setup
/// - Uses fork testing against Sepolia testnet to access required declared contracts maintained by
/// the garaga team - Loads proof calldata from `tests/proof_calldata.txt`
/// - To generate the calldata, you can use the garaga CLI:
/// ```bash
/// garaga calldata
///     --system groth16
///     --vk path/to/vk
///     --proof path/to/proof
///     --public-inputs path/to/public_inputs
///     --format snforge
///     --output-path path/to/tests
/// ```
/// This will generate a file `proof_calldata.txt` in the specified output path.
/// You can then use this file in the test.
///
/// ## Expected Behavior
/// - The proof should verify successfully
/// - The function should return Ok(public_inputs) containing the expected public inputs
/// - No panics or assertion failures should occur
#[test]
#[fork(url: "https://starknet-sepolia-rpc.publicnode.com", block_tag: latest)]
fn test_verify_groth16_proof_bn254() {
    // Step 1: Declare the verification contract
    let class_hash = declare_contract("Groth16VerifierBN254");
    let dispatcher = IGroth16VerifierBN254LibraryDispatcher { class_hash };

    // Step 2: Load the proof fixture generated by the script
    // This file contains the groth16 proof calldata formatted for Starknet
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file).span();

    // Step 3: Verify the proof on-chain
    // This calls the contract's verify_groth16_proof_bn254 function with the loaded proof data
    let result = dispatcher.verify_groth16_proof_bn254(calldata);

    // Step 4: Assert that this exact synthetic dispute verified.
    assert(result.is_ok(), 'Proof verification failed');
    let public_inputs = result.unwrap();
    assert_eq!(public_inputs.len(), 8);
    assert_eq!(*public_inputs.at(0), 1001_u256);
    assert_eq!(*public_inputs.at(1), 2001_u256);
    assert_eq!(*public_inputs.at(2), 3001_u256);
    assert_eq!(*public_inputs.at(3), 80_u256);
    assert_eq!(
        *public_inputs.at(4),
        12318210310005545467923238974225569704656499382605073888978048422405465896216_u256,
    );
    assert_eq!(
        *public_inputs.at(5),
        7027575617398834524868433602045773688065798774486261216253352711849780969765_u256,
    );
    assert_eq!(*public_inputs.at(6), 2_u256);
    assert_eq!(*public_inputs.at(7), 2000000000_u256);
}

#[test]
#[feature("safe_dispatcher")]
#[fork(url: "https://starknet-sepolia-rpc.publicnode.com", block_tag: latest)]
fn test_tampered_public_signal_does_not_verify() {
    let class_hash = declare_contract("Groth16VerifierBN254");
    let dispatcher = IGroth16VerifierBN254SafeLibraryDispatcher { class_hash };
    let file = FileTrait::new("tests/proof_calldata.txt");
    let mut calldata = read_txt(@file);
    let mut tampered = array![];

    // Index 33 is the low limb of the first public input after the proof points
    // and public-input array length. The proof and its hints remain unchanged.
    for _ in 0_usize..33_usize {
        tampered.append(calldata.pop_front().unwrap());
    }
    tampered.append(calldata.pop_front().unwrap() + 1);
    tampered.append_span(calldata.span());

    let result = dispatcher.verify_groth16_proof_bn254(tampered.span());
    assert(result.is_err(), 'Tampered proof accepted');
}

/// Proves that Gigstark's settlement verifier accepts the generated proof
/// through the real Garaga verifier contract, not a mock verifier boundary.
#[test]
#[fork(url: "https://starknet-sepolia-rpc.publicnode.com", block_tag: latest)]
fn test_real_proof_authorizes_gigstark_settlement() {
    let groth16_class = declare(contract: "Groth16VerifierBN254")
        .unwrap_syscall()
        .contract_class();
    let (groth16_address, _) = groth16_class.deploy(@array![]).unwrap_syscall();

    let compute_class = declare(contract: "GigstarkComputeVerifier")
        .unwrap_syscall()
        .contract_class();
    let admin: ContractAddress = 9001.try_into().unwrap();
    let audience: ContractAddress = 4001.try_into().unwrap();
    let (compute_address, _) = compute_class.deploy(@array![admin.into()]).unwrap_syscall();
    let compute = IGigstarkComputeVerifierDispatcher { contract_address: compute_address };

    start_cheat_caller_address(compute_address, admin);
    compute
        .set_policy(
            2001,
            audience,
            3001,
            5001,
            80,
            0,
            2_100_000_000,
            groth16_address,
        );
    start_cheat_block_timestamp(compute_address, 1_900_000_000);

    let result = GigstarkZkResult {
        policy_id: 2001,
        audience,
        job_id: 6001,
        input_commitment: 1001,
        evidence_commitment: 12318210310005545467923238974225569704656499382605073888978048422405465896216_u256,
        result_commitment: 7027575617398834524868433602045773688065798774486261216253352711849780969765_u256,
        outcome: COMPUTE_OUTCOME_SELLER,
        expires_at: 2_000_000_000,
        oyster_receipt_commitment: 333_u256,
    };
    let file = FileTrait::new("tests/proof_calldata.txt");
    let calldata = read_txt(@file);

    start_cheat_caller_address(compute_address, audience);
    let outcome = compute.consume_result(6001, 1001, result, calldata.span());

    assert_eq!(outcome, COMPUTE_OUTCOME_SELLER);
    assert(compute.is_nullifier_used(compute.get_result_nullifier(result)), 'Result not consumed');
}
