"use client";

import { useEffect, useMemo, useState } from "react";
import {
  EMPTY_MARKETPLACE, acceptProposal, appendFeedPost, createGig, fundOrder, recordDelivery,
  reputationFor, settleOrder, submitProposal, upsertProfile,
  type GigstarkProfile, type MarketplaceState,
} from "../lib/marketplace";

const STORAGE_KEY = "zeerostream.marketplace.v1";

function id(prefix: string) { return `${prefix}-${crypto.randomUUID()}`; }

function encode(state: MarketplaceState) {
  return JSON.stringify({ ...state, gigs: state.gigs.map((gig) => ({ ...gig, price: gig.price.toString() })), orders: state.orders.map((order) => ({ ...order, amount: order.amount.toString() })), receipts: state.receipts.map((receipt) => ({ ...receipt, amount: receipt.amount.toString() })) });
}

function decode(value: string | null): MarketplaceState {
  if (!value) return EMPTY_MARKETPLACE;
  try {
    const parsed = JSON.parse(value) as MarketplaceState & { gigs: Array<{ price: string }>; orders: Array<{ amount: string }>; receipts: Array<{ amount: string }> };
    return { ...parsed, gigs: parsed.gigs.map((gig) => ({ ...gig, price: BigInt(gig.price) })), orders: parsed.orders.map((order) => ({ ...order, amount: BigInt(order.amount) })), receipts: parsed.receipts.map((receipt) => ({ ...receipt, amount: BigInt(receipt.amount) })) };
  } catch { return EMPTY_MARKETPLACE; }
}

export function MarketplaceWorkspace() {
  const [state, setState] = useState<MarketplaceState>(EMPTY_MARKETPLACE);
  const [ready, setReady] = useState(false);
  const [profile, setProfile] = useState({ handle: "", displayName: "", role: "both" as GigstarkProfile["role"], starkName: "", bio: "" });
  const [gig, setGig] = useState({ creatorId: "", title: "", category: "", description: "", price: "" });
  const [proposal, setProposal] = useState({ gigId: "", buyerId: "", message: "" });
  const [post, setPost] = useState({ creatorId: "", tier: "supporter" as const, body: "" });
  const [notice, setNotice] = useState("Local workspace ready. Nothing here is public, shared, or paid until an approved backend and wallet flow exist.");

  useEffect(() => { setState(decode(localStorage.getItem(STORAGE_KEY))); setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(STORAGE_KEY, encode(state)); }, [ready, state]);
  const profiles = state.profiles;
  const profileName = (profileId: string) => profiles.find(({ id }) => id === profileId)?.displayName ?? "Unknown profile";
  const act = (operation: () => MarketplaceState, success: string) => { try { setState(operation()); setNotice(success); } catch (error) { setNotice(error instanceof Error ? error.message : "MARKETPLACE_ACTION_FAILED"); } };
  const canCreateGig = profiles.some((entry) => entry.id === gig.creatorId);
  const stats = useMemo(() => ({ gigs: state.gigs.length, openOrders: state.orders.filter(({ status }) => !["settled", "refunded"].includes(status)).length, receipts: state.receipts.length }), [state]);

  return <section className="marketplace" id="marketplace" aria-labelledby="marketplace-title">
    <div className="marketplace-heading"><div><p className="eyebrow">Local product workspace</p><h2 id="marketplace-title">Build the storefront before enabling settlement.</h2><p>Profiles, listings, proposals, orders, receipts, reputation, and tier posts persist only in this browser. They are a local operational model—not a public marketplace or payment record.</p></div><div className="market-stats"><b>{stats.gigs}</b><span>gigs</span><b>{stats.openOrders}</b><span>active orders</span><b>{stats.receipts}</b><span>local receipts</span></div></div>
    <p className="notice" role="status">{notice}</p>
    <div className="market-grid">
      <form className="market-card" onSubmit={(event) => { event.preventDefault(); const next = { id: id("profile"), ...profile, starkName: profile.starkName.trim() || undefined, bio: profile.bio.trim() || undefined }; act(() => upsertProfile(state, next), "Profile saved locally."); setProfile({ handle: "", displayName: "", role: "both", starkName: "", bio: "" }); }}><p className="eyebrow">1 · identity</p><h3>Optional .stark profile</h3><input required placeholder="Display name" value={profile.displayName} onChange={(e) => setProfile({ ...profile, displayName: e.target.value })}/><input required placeholder="Handle" value={profile.handle} onChange={(e) => setProfile({ ...profile, handle: e.target.value })}/><input placeholder="Optional name.stark (not resolved)" value={profile.starkName} onChange={(e) => setProfile({ ...profile, starkName: e.target.value })}/><select value={profile.role} onChange={(e) => setProfile({ ...profile, role: e.target.value as GigstarkProfile["role"] })}><option value="both">Buyer and creator</option><option value="creator">Creator</option><option value="buyer">Buyer</option></select><textarea placeholder="Short public bio" value={profile.bio} onChange={(e) => setProfile({ ...profile, bio: e.target.value })}/><button>Save profile</button></form>
      <form className="market-card" onSubmit={(event) => { event.preventDefault(); act(() => createGig(state, { id: id("gig"), creatorId: gig.creatorId, title: gig.title, category: gig.category, description: gig.description, price: BigInt(gig.price), status: "open" }), "Gig published in this browser only."); setGig({ creatorId: "", title: "", category: "", description: "", price: "" }); }}><p className="eyebrow">2 · supply</p><h3>Create a gig</h3><select required value={gig.creatorId} onChange={(e) => setGig({ ...gig, creatorId: e.target.value })}><option value="">Choose creator</option>{profiles.map((entry) => <option key={entry.id} value={entry.id}>{entry.displayName}</option>)}</select><input required placeholder="Gig title" value={gig.title} onChange={(e) => setGig({ ...gig, title: e.target.value })}/><input required placeholder="Category" value={gig.category} onChange={(e) => setGig({ ...gig, category: e.target.value })}/><textarea required placeholder="What will be delivered? Keep delivery content off-chain." value={gig.description} onChange={(e) => setGig({ ...gig, description: e.target.value })}/><input required min="1" inputMode="numeric" placeholder="Raw token amount" value={gig.price} onChange={(e) => setGig({ ...gig, price: e.target.value })}/><button disabled={!canCreateGig}>Create local gig</button></form>
      <form className="market-card" onSubmit={(event) => { event.preventDefault(); act(() => submitProposal(state, { id: id("proposal"), ...proposal, status: "pending" }), "Proposal submitted locally for creator review."); setProposal({ gigId: "", buyerId: "", message: "" }); }}><p className="eyebrow">3 · demand</p><h3>Send a proposal</h3><select required value={proposal.gigId} onChange={(e) => setProposal({ ...proposal, gigId: e.target.value })}><option value="">Choose gig</option>{state.gigs.filter(({ status }) => status === "open").map((entry) => <option key={entry.id} value={entry.id}>{entry.title} · {entry.price.toString()}</option>)}</select><select required value={proposal.buyerId} onChange={(e) => setProposal({ ...proposal, buyerId: e.target.value })}><option value="">Choose buyer</option>{profiles.map((entry) => <option key={entry.id} value={entry.id}>{entry.displayName}</option>)}</select><textarea required placeholder="Scope, timing, and acceptance criteria" value={proposal.message} onChange={(e) => setProposal({ ...proposal, message: e.target.value })}/><button>Submit proposal</button></form>
    </div>
    <div className="market-list"><div><p className="eyebrow">Listings</p>{state.gigs.length === 0 ? <p className="muted">Create a profile and gig to start a local catalog.</p> : state.gigs.map((entry) => <article key={entry.id}><b>{entry.title}</b><span>{entry.category} · {entry.price.toString()} raw units · {profileName(entry.creatorId)}</span><small>{entry.description}</small></article>)}</div><div><p className="eyebrow">Proposals</p>{state.proposals.length === 0 ? <p className="muted">No proposals yet.</p> : state.proposals.map((entry) => <article key={entry.id}><b>{profileName(entry.buyerId)} → {state.gigs.find(({ id }) => id === entry.gigId)?.title ?? "Gig"}</b><span>{entry.status}</span><small>{entry.message}</small>{entry.status === "pending" ? <button className="secondary" onClick={() => act(() => acceptProposal(state, entry.id, id("order")), "Proposal accepted; order awaits an explicitly reviewed payment.")}>Accept proposal</button> : null}</article>)}</div></div>
    <div className="market-orders"><p className="eyebrow">Order desk · local lifecycle only</p>{state.orders.length === 0 ? <p className="muted">Accepted proposals will appear here. No wallet action is available from this desk.</p> : state.orders.map((order) => <article key={order.id}><div><b>{state.gigs.find(({ id }) => id === order.gigId)?.title ?? "Gig"}</b><span>{order.status} · {order.amount.toString()} raw units</span></div><div className="order-actions">{order.status === "awaiting_payment" ? <><button onClick={() => act(() => fundOrder(state, order.id, id("receipt")), "Local deposit-review receipt recorded. Use the guarded Wallet API review before any real signature.")}>Record reviewed deposit</button><a className="button secondary-link" href="#wallet-check">Open guarded wallet review</a></> : null}{order.status === "funded" ? <button onClick={() => act(() => recordDelivery(state, order.id, `delivery-${Date.now().toString(36)}`), "Delivery commitment recorded locally; delivery content is not stored.")}>Record delivery commitment</button> : null}{order.status === "delivered" ? <><button onClick={() => act(() => settleOrder(state, order.id, "seller_claim", id("receipt")), "Local seller-claim receipt recorded.")}>Record seller claim</button><button className="secondary" onClick={() => act(() => settleOrder(state, order.id, "refund", id("receipt")), "Local refund receipt recorded.")}>Record refund</button></> : null}</div></article>)}</div>
    <div className="market-grid market-bottom"><form className="market-card" onSubmit={(event) => { event.preventDefault(); act(() => appendFeedPost(state, { id: id("post"), ...post }), "Tier post saved locally. Access enforcement requires the reviewed tier-proof route."); setPost({ creatorId: "", tier: "supporter", body: "" }); }}><p className="eyebrow">Tier feed</p><h3>Creator update</h3><select required value={post.creatorId} onChange={(e) => setPost({ ...post, creatorId: e.target.value })}><option value="">Choose creator</option>{profiles.map((entry) => <option key={entry.id} value={entry.id}>{entry.displayName}</option>)}</select><select value={post.tier} onChange={(e) => setPost({ ...post, tier: e.target.value as typeof post.tier })}><option value="supporter">Supporter</option><option value="patron">Patron</option><option value="studio">Studio</option></select><textarea required placeholder="Share an update without private delivery evidence." value={post.body} onChange={(e) => setPost({ ...post, body: e.target.value })}/><button>Save local post</button></form><div className="market-card"><p className="eyebrow">Reputation</p><h3>Verified only by completed orders</h3>{profiles.length === 0 ? <p className="muted">Profiles will gain local reputation after settlement.</p> : profiles.map((entry) => { const score = reputationFor(state, entry.id); return <p className="reputation" key={entry.id}><b>{entry.displayName}</b><span>{score.score} score · {score.completed} settled · {score.refunded} refunded</span></p>; })}<p className="muted">Scores are local UI signals, never an identity assertion or an onchain reputation claim.</p></div><div className="market-card"><p className="eyebrow">Payment history</p><h3>Receipts need wallet proof</h3>{state.receipts.length === 0 ? <p className="muted">Local receipt records appear after an order transition.</p> : state.receipts.map((receipt) => <p className="reputation" key={receipt.id}><b>{receipt.kind}</b><span>{receipt.amount.toString()} · {receipt.status}</span></p>)}<p className="muted">A real receipt requires a reviewed wallet submission and confirmed transaction; these records cannot claim either.</p></div></div>
    {state.feed.length ? <div className="feed"><p className="eyebrow">Local creator feed</p>{state.feed.map((entry) => <article key={entry.id}><b>{profileName(entry.creatorId)} · {entry.tier}</b><p>{entry.body}</p></article>)}</div> : null}
  </section>;
}
