[package]
name = "gigstark-enclave"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ark-bn254 = "=0.5.0"
ark-ff = "=0.5.0"
light-poseidon = "=0.4.0"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"

[target.'cfg(target_os = "linux")'.dependencies]
vsock = "=0.5.2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = true
